# Generated by Django 6.0.7 on 2026-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu_item_description', models.TextField(default='', max_length=1000)),
                ('inventory', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('reservation_date', models.DateField()),
                ('reservation_slot', models.TimeField(default='19:00:00')),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_slot'],
                'unique_together': {('reservation_date', 'reservation_slot')},
            },
        ),
    ]
